//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigmuTest2
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_CUST_ACCOUNT_CRM
    {
        public string CONT_ID { get; set; }
        public string SERVICE_ID { get; set; }
        public string CUST_NAME { get; set; }
        public string MOBILE_NO { get; set; }
        public string EMAIL { get; set; }
        public string CUST_ACC_ADDR { get; set; }
        public string ZIP_ID { get; set; }
        public string COUNTY_NAME { get; set; }
        public string TOWN_NAME { get; set; }
        public string RSYS_ID { get; set; }
        public string SERVICE_TYPE { get; set; }
        public System.DateTime TRANS_DATE { get; set; }
    }
}
