//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncSeomcMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_CUST_ACCOUNT_CRM_BM
    {
        public string CUST_ACC_IDNO { get; set; }
        public string CUST_ACC_NAME { get; set; }
        public string CUST_ACC_ADDR { get; set; }
        public Nullable<decimal> SRV_FEE { get; set; }
        public Nullable<decimal> BILLING_AMT { get; set; }
        public string SERVICE_TYPE { get; set; }
        public System.DateTime TRANS_DATE { get; set; }
        public string ZIP_ID { get; set; }
        public string COUNTY_NAME { get; set; }
        public string TOWN_NAME { get; set; }
        public Nullable<bool> GEOCODING_TAG { get; set; }
    }
}
