//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncSeomcMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_CUST_ACCOUNT_CRM_BD
    {
        public string CUST_ACC_IDNO { get; set; }
        public string CONT_ID { get; set; }
        public string SERVICE_ID { get; set; }
        public string CUST_NAME { get; set; }
        public string MOBILE_NO { get; set; }
        public string RSYS_ID { get; set; }
        public string SERVICE_TYPE { get; set; }
        public System.DateTime TRANS_DATE { get; set; }
    }
}
