//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SigmuTest2
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_SP_PROCESS
    {
        public string SP_NAME { get; set; }
        public string LAST_TRANS_VALUE { get; set; }
        public Nullable<int> RECALL_DAY { get; set; }
        public Nullable<bool> TRUNCATE_FLAG { get; set; }
        public string RUN_MESSAGE { get; set; }
        public string MEMO { get; set; }
    }
}
