//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncSeomcMember
{
    using System;
    using System.Collections.Generic;
    
    public partial class F_SP_PROCESS
    {
        public string SP_NAME { get; set; }
        public string LAST_TRANS_VALUE { get; set; }
        public Nullable<int> RECALL_DAY { get; set; }
        public Nullable<bool> TRUNCATE_FLAG { get; set; }
        public string RUN_MESSAGE { get; set; }
        public string MEMO { get; set; }
    }
}
